#!/bin/sh
set -o nounset -o errexit

temp_dir=$(mktemp -d)

cleanup() {
  rm -rf "$temp_dir"
}

trap cleanup EXIT

if test "${1+SET}" = SET && test "$1" = "update-me"
then
  # shellcheck disable=SC2064
  curl --fail --location --output "$temp_dir"/2e1b35b https://raw.githubusercontent.com/knaka/gorun/refs/heads/main/gorun
  cat "$temp_dir"/2e1b35b > "$0"
  exit 0
fi

main_file_path="$temp_dir/main.go"
cat <<'EMBED_FAA58B3' > "$main_file_path"
package main

import (
	"crypto/sha1"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
)

func v0(err error) {
	if err != nil {
		panic(err)
	}
}

func v[T any](t T, err error) T {
	if err != nil {
		panic(err)
	}
	return t
}

func v2[T any, U any](t T, u U, err error) (T, U) {
	if err != nil {
		panic(err)
	}
	return t, u
}

var exeExt = sync.OnceValue(func() (exeExt string) {
	switch runtime.GOOS {
	case "windows":
		exeExt = ".exe"
	}
	return
})

var Goroot = sync.OnceValues(func() (gobinPath string, err error) {
	// 1.22.7 seems not working on Windows?
	ver := "1.23.1"
	homeDir := v(os.UserHomeDir())
	sdkDirPath := filepath.Join(homeDir, "sdk")
	gorootPath := filepath.Join(sdkDirPath, "go"+ver)
	goCmdPath := filepath.Join(gorootPath, "bin", "go"+exeExt())
	if _, err := os.Stat(goCmdPath); err == nil {
		return gorootPath, nil
	}
	tempDir := v(os.MkdirTemp("", ""))
	defer (func() { v0(os.RemoveAll(tempDir)) })()
	arcPath := filepath.Join(tempDir, "temp.tgz")
	url := fmt.Sprintf("https://go.dev/dl/go%s.%s-%s.tar.gz", ver, runtime.GOOS, runtime.GOARCH)
	//goland:noinspection GoBoolExpressions
	if runtime.GOOS == "windows" {
		arcPath = filepath.Join(tempDir, "temp.zip")
		url = fmt.Sprintf("https://go.dev/dl/go%s.%s-%s.zip", ver, runtime.GOOS, runtime.GOARCH)
	}
	cmd := exec.Command("curl"+exeExt(), "--location", "-o", arcPath, url)
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	v0(cmd.Run())
	cmd = exec.Command("tar"+exeExt(), "-C", sdkDirPath, "-xzf", arcPath)
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	v0(cmd.Run())
	v0(os.Rename(filepath.Join(sdkDirPath, "go"), gorootPath))
	return gorootPath, nil
})

var goCmdPath = sync.OnceValue(func() string {
	binDirPath := filepath.Join(v(Goroot()), "bin")
	v0(os.Setenv("PATH", fmt.Sprintf("%s%c%s", binDirPath, filepath.ListSeparator, os.Getenv("PATH"))))
	cmdPath := filepath.Join(binDirPath, "go"+exeExt())
	return cmdPath
})

// EnsureInstalled ensures that the program package is installed.
func EnsureInstalled(
	gobinPath string,
	pkgPath string,
	ver string,
	tags string,
	verbose bool,
) (
	cmdPath string,
	err error,
) {
	pkgBase := path.Base(pkgPath)
	pkgBaseVer := pkgBase + "@" + ver
	if tags != "" {
		hash := sha1.New()
		hash.Write([]byte(tags))
		sevenDigits := fmt.Sprintf("%x", hash.Sum(nil))[:7]
		pkgBaseVer += "-" + sevenDigits
	}
	cmdPath = filepath.Join(gobinPath, pkgBaseVer+exeExt())
	if _, err_ := os.Stat(cmdPath); err_ != nil {
		if verbose {
			log.Printf("Installing %s@%s\n", pkgPath, ver)
		}
		args := []string{"install"}
		if tags != "" {
			log.Printf("Installing with tags %s\n", tags)
			args = append(args, "-tags", tags)
		}
		args = append(args, fmt.Sprintf("%s@%s", pkgPath, ver))
		if verbose {
			log.Printf("Installing %s@%s\n", pkgPath, ver)
			log.Printf("Arguments: %v\n", args)
		}
		cmd := exec.Command(goCmdPath(), args...)
		cmd.Env = append(os.Environ(), fmt.Sprintf("GOBIN=%s", gobinPath))
		cmd.Stdout = os.Stderr
		cmd.Stderr = os.Stderr
		_ = os.Remove(cmdPath)
		v0(cmd.Run())
		_ = os.Remove(cmdPath)
		v0(os.Rename(filepath.Join(gobinPath, pkgBase), cmdPath))
	}
	return
}

func main() {
	verbose := flag.Bool("verbose", false, "Verbose output.")
	shouldHelp := flag.Bool("help", false, "Show help.")
	tags := flag.String("tags", "", "Build tags.")
	flag.Usage = func() {
		_, _ = fmt.Fprintln(os.Stderr, `Usage: gorun [options] <package> [<args>...]

Options:`)
		flag.PrintDefaults()
		_, _ = fmt.Fprintln(os.Stderr, `Examples:

  gorun --tags netgo,sqlite3 golang.org/x/tools/cmd/stringer@@v0.11 -type=MyType
`)
	}
	flag.Parse()
	if *shouldHelp {
		flag.Usage()
		os.Exit(0)
	}
	if *verbose {
		_, _ = fmt.Fprintln(os.Stderr, "Verbose output")
		_, _ = fmt.Fprintf(os.Stderr, "Build tags: %s\n", *tags)
	}
	if flag.NArg() == 0 {
		_, _ = fmt.Fprintln(os.Stderr, "No package specified.")
		os.Exit(1)
	}
	packagePathVer := flag.Arg(0)
	args := flag.Args()[1:]
	if *verbose {
		_, _ = fmt.Fprintf(os.Stderr, "Package: %s\n", packagePathVer)
		_, _ = fmt.Fprintf(os.Stderr, "Arguments: %v\n", args)
	}
	gorootPath, err := Goroot()
	if err != nil {
		log.Fatalf("Error: %+v", err)
	}
	if *verbose {
		_, _ = fmt.Fprintf(os.Stderr, "GOROOT: %s\n", gorootPath)
	}
	homeDir := v(os.UserHomeDir())
	divs := strings.SplitN(packagePathVer, "@", 2)
	packagePath := divs[0]
	packageVer := divs[1]
	cmdPath, err := EnsureInstalled(
		filepath.Join(homeDir, ".gorun"),
		packagePath,
		packageVer,
		*tags,
		*verbose,
	)
	if err != nil {
		log.Fatalf("Error: %+v", err)
	}
	cmd := exec.Command(cmdPath, args...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	var execErr *exec.ExitError
	err = cmd.Run()
	errors.As(err, &execErr)
	if execErr != nil {
		os.Exit(execErr.ExitCode())
	}
}
EMBED_FAA58B3

is_windows() {
  case "$(uname -s)" in
    (Windows_NT|CYGWIN*|MINGW*|MSYS*) return 0 ;;
    (*) return 1 ;;
  esac
}

# shellcheck disable=SC2120
sort_version() {
  sed -E -e '/-/! { s/^([^.]+(\.[^.]+){2})$/\1_/; }' -e 's/-patch/_patch/' | sort -V "$@" | sed -e 's/_$//' -e 's/_patch/-patch/'
}

# Check if the version is greater than the specified version.
version_gt() {
  test "$(printf '%s\n' "$@" | sort_version | head -n 1)" != "$1"
}

version_ge() {
  test "$(printf '%s\n' "$@" | sort_version -r | head -n 1)" = "$1"
}

# All releases - The Go Programming Language https://go.dev/dl/
go_required_min_ver=go1.23.1

echo_go_paths() (
  # $GOROOT
  if test "${GOROOT+set}" = set
  then
    echo "$GOROOT"
  fi
  # `go` command
  if type go > /dev/null 2>&1
  then
    go env GOROOT
  fi
  # System-wide installation
  if is_windows
  then
    echo "C:/Program Files/Go"
  else
    echo "/usr/local/go"
  fi
  # Automatically installed SDKs
  find "$HOME"/sdk -maxdepth 1 -type d -name 'go*' | sort -r
)

# Returns the path to the Go root directory.
goroot_path() (
  goroot="$(
    export GOTOOLCHAIN=local
    echo_go_paths | while read -r go_dir_path
    do
      if type "$go_dir_path"/bin/go >/dev/null 2>&1 && version_ge "$("$go_dir_path"/bin/go env GOVERSION)" "$go_required_min_ver"
      then
        echo "$go_dir_path"
        break
      fi
    done
  )"
  if test -n "$goroot"
  then
    echo "$goroot"
    return 0
  fi

  # If no Go installation is found, install the required version.
  sdk_dir_path="$HOME"/sdk
  goroot="$sdk_dir_path"/${go_required_min_ver}
  case "$(uname -s)" in
    Linux) goos=linux;;
    Darwin) goos=darwin;;
    Windows_NT) goos=windows;;
    *)
      echo "Unsupported OS: $(uname -s)" >&2
      exit 1;;
  esac
  case "$(uname -m)" in
    arm64) goarch=arm64;;
    x86_64) goarch=amd64;;
    *)
      echo "Unsupported architecture: $(uname -m)" >&2
      exit 1;;
  esac
  mkdir -p "$sdk_dir_path"
  rm -fr "$sdk_dir_path"/go
  if is_windows
  then
    zip_path="$(temp_dir_path)"/temp.zip
    curl --location -o "$zip_path" "https://go.dev/dl/$go_required_min_ver.$goos-$goarch.zip"
    (
      cd "$sdk_dir_path" || exit 1
      unzip -q "$zip_path" >&2
    )
  else
    curl --location -o - "https://go.dev/dl/$go_required_min_ver.$goos-$goarch.tar.gz" | (cd "$sdk_dir_path" || exit 1; tar -xzf -)
  fi
  mv "$sdk_dir_path"/go "$goroot"
  echo "$goroot"
)

gopath="${GOPATH:-$HOME/go}"
mkdir -p "$gopath"/bin
unique_name=$(realpath "$0" | tr / _)
cmd_path="$gopath"/bin/embedded-"$unique_name"
if test -z "$(find "$cmd_path" -newer "$0" 2>/dev/null)"
then
  (
    GOROOT="$(goroot_path)"
    echo Compiling "$0" to "$cmd_path" with Go in "$GOROOT" >&2
    export GOROOT
    PATH="$GOROOT"/bin:$PATH
    export PATH 
    go build -o "$cmd_path" "$main_file_path"
  )
fi

cleanup

exec "$cmd_path" "$@"
